package com.cd.test.operation.taskManagement.service;

import com.alibaba.fastjson.JSON;
import com.cd.test.common.Constants;
import com.cd.test.common.LoggerProxy;
import com.cd.test.common.PoiUtils;
import lombok.extern.log4j.Log4j2;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.ss.usermodel.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

@Log4j2
@Service
public class TaskManagementServiceImpl implements TaskManagementService {
    @Autowired
    LoggerProxy loggerProxy;

    /**
     * 解析Excel文件
     * @return
     */
    @Override
    public List excelFileExecution() {
        List list = new ArrayList();
        // Use a file
        try (Workbook wb = WorkbookFactory.create(new File("D:\\TaskManagement\\task-management.xlsx"))) {
            int numberOfSheets = wb.getNumberOfSheets();
            //Iterate over Sheets
            for (int sheetIndex = 0; sheetIndex < numberOfSheets; sheetIndex++) {
                List sheetList = new ArrayList();
                Sheet sheetAt = wb.getSheetAt(sheetIndex);
                // Decide which rows to process
                int rowStart = Math.min(0, sheetAt.getFirstRowNum());
                int rowEnd = Math.max(1400, sheetAt.getLastRowNum());
                //Iterate over Rows
                for (int rowNum = rowStart; rowNum < rowEnd; rowNum++) {
                    Map rowMap = new HashMap();
                    Row row = sheetAt.getRow(rowNum);
                    if (row == null) {
                        // This whole row is empty
                        // Handle it as needed
                        continue;
                    }

                    //Iterate over Cell
                    int lastColumn = Math.max(row.getLastCellNum(), Constants.MY_MINIMUM_COLUMN_COUNT);
                    for (int cn = 0; cn < lastColumn; cn++) {
                        Cell cell = row.getCell(cn, Row.RETURN_BLANK_AS_NULL);
                        if (cell == null) {
                            // The spreadsheet is empty in this cell
                            rowMap.put(cn, Constants.REPLACEMENT_EMPTY_STRING);
                        } else {
                            // Do something useful with the cell's contents
//                            rowMap.put(cn, );
                            rowMap.put(cn, PoiUtils.cellValue(cell));
                        }
                    }
                    sheetList.add(rowNum, rowMap);


//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));
//                    log.info("excelFileExecution: " + JSON.toJSONString(rowMap));


                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                    loggerProxy.info("excelFileExecution: " + JSON.toJSONString(rowMap));
                }
                list.add(sheetIndex, sheetList);
            }
        } catch (IOException e) {
            loggerProxy.error(e);
        } catch (InvalidFormatException e) {
            loggerProxy.error(e);
        }
        return list;
    }



}
    